-- PostgreSQL (ejecutar en DBeaver)
-- Objetivo: crear tabla auxiliar para ingesta de impresión desde SAP.
-- Convención: external_id es la clave única de negocio.

BEGIN;

CREATE SCHEMA IF NOT EXISTS sap;

CREATE TABLE IF NOT EXISTS sap.print_queue_aux (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(120) NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    store_code VARCHAR(20) NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pdf_blob BYTEA NOT NULL,

    processed BOOLEAN NOT NULL DEFAULT FALSE,
    claimed_by VARCHAR(120) NULL,
    lease_expires_at_utc TIMESTAMPTZ NULL,
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_print_queue_aux_external_id UNIQUE (external_id),
    CONSTRAINT ck_print_queue_aux_document_type
        CHECK (document_type IN ('CALLCENTER', 'ALBARAN', 'FACTURA', 'AD360'))
);

CREATE INDEX IF NOT EXISTS ix_print_queue_aux_claim
    ON sap.print_queue_aux (processed, lease_expires_at_utc, created_at_utc);

CREATE INDEX IF NOT EXISTS ix_print_queue_aux_store_code
    ON sap.print_queue_aux (store_code);

CREATE OR REPLACE FUNCTION sap.trg_set_updated_at_utc()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at_utc := NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_print_queue_aux_updated_at ON sap.print_queue_aux;
CREATE TRIGGER trg_print_queue_aux_updated_at
BEFORE UPDATE ON sap.print_queue_aux
FOR EACH ROW
EXECUTE FUNCTION sap.trg_set_updated_at_utc();

COMMIT;

-- ==========================================
-- CLAIM BATCH (ejemplo de ejecución)
-- ==========================================
-- Cambia:
--   :worker_id  -> identificador del worker (ej: worker-01)
--   :lease_sec  -> segundos de lease (ej: 15)
--   :batch_size -> tamaño del lote (ej: 25)
--
-- Nota: en DBeaver puedes reemplazar manualmente los valores.
/*
WITH candidates AS (
    SELECT q.id
    FROM sap.print_queue_aux q
    WHERE q.processed = FALSE
      AND (q.lease_expires_at_utc IS NULL OR q.lease_expires_at_utc <= NOW())
    ORDER BY q.created_at_utc, q.id
    LIMIT 25
    FOR UPDATE SKIP LOCKED
),
claimed AS (
    UPDATE sap.print_queue_aux q
    SET claimed_by = 'worker-01',
        lease_expires_at_utc = NOW() + make_interval(secs => 15),
        updated_at_utc = NOW()
    FROM candidates c
    WHERE q.id = c.id
    RETURNING q.id, q.external_id, q.document_type, q.store_code, q.created_at_utc, q.pdf_blob
)
SELECT *
FROM claimed
ORDER BY created_at_utc, id;
*/

-- ==========================================
-- ACK PROCESSED (ejemplo de ejecución)
-- ==========================================
-- Recomendado: ejecutar después de persistir en local con éxito.
-- El filtro claimed_by evita ack accidental de otro worker.
/*
UPDATE sap.print_queue_aux q
SET processed = TRUE,
    claimed_by = NULL,
    lease_expires_at_utc = NULL,
    updated_at_utc = NOW()
WHERE q.external_id = ANY (ARRAY['ALB-10001','ALB-10002'])
  AND q.claimed_by = 'worker-01';
*/
